# Generated by Django 2.2 on 2019-06-22 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='dashboard', max_length=128)),
                ('action_params', models.TextField(default='')),
                ('request_type', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('DELETE', 'DELETE'), ('UPDATE', 'UPDATE')], default='GET', max_length=128)),
                ('request_source', models.CharField(choices=[('API', 'API'), ('UI', 'UI')], default='UI', max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('ip_region', models.CharField(blank=True, max_length=255)),
                ('ip_city', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True)),
                ('device_type', models.CharField(choices=[('pc', 'PC'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('device', models.CharField(blank=True, max_length=30)),
                ('browser', models.CharField(blank=True, max_length=30)),
                ('browser_version', models.CharField(blank=True, max_length=30)),
                ('system', models.CharField(blank=True, max_length=30)),
                ('system_version', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
